/**
 * Bundles the MCP App workspace into one self-contained HTML asset and embeds
 * it as a TypeScript module the server imports. No external CDN, fonts or
 * scripts: the App SDK and all view code are inlined, and the HTML is compiled
 * into the server JS so the stdio, HTTP and serverless Worker entrypoints serve
 * byte-identical markup with no runtime filesystem read.
 *
 * Outputs:
 *   dist/app.html                    — the bundled HTML (inspectable, shipped in the npm tarball)
 *   src/generated/workspace-html.ts  — `export const WORKSPACE_HTML = "…"` (compiled by tsc)
 */
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const entry = resolve(root, 'src/apps/workspace/entry.ts');
const cssPath = resolve(root, 'src/apps/workspace/styles.css');

const result = await build({
  entryPoints: [entry],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  sourcemap: false,
  legalComments: 'none',
});

if (result.outputFiles.length !== 1) {
  throw new Error(`expected one bundle output, got ${result.outputFiles.length}`);
}

const css = readFileSync(cssPath, 'utf8');
// Defensive: never let inline script content terminate the <script> element.
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>getcompetitive workspace</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${js}</script>
</body>
</html>`;

mkdirSync(resolve(root, 'dist'), { recursive: true });
writeFileSync(resolve(root, 'dist/app.html'), html);

const asset = `/**
 * Generated by \`scripts/build-app.mjs\` — do not edit by hand.
 * Holds the bundled MCP App workspace HTML (inlined CSS + JS), so the stdio,
 * HTTP and serverless entrypoints serve byte-identical markup with no runtime
 * filesystem read.
 */
export const WORKSPACE_HTML = ${JSON.stringify(html)};
`;

mkdirSync(resolve(root, 'src/generated'), { recursive: true });
writeFileSync(resolve(root, 'src/generated/workspace-html.ts'), asset);

console.error(`workspace: dist/app.html (${(html.length / 1024).toFixed(1)} KiB) -> src/generated/workspace-html.ts`);
