// Maintenance script: rebuild the sprite id table.
// Usage: node scripts/build-sprites.mjs   -> writes src/sprites.data.ts
//
// `get_sprites` returns sprite URLs, and the server must stay a pure read over
// committed data — no network at runtime (see src/result.ts). PokéAPI assigns
// form ids above 10000 that follow neither the National Dex number nor the forme
// name (Lucario-Mega is dex 448 but sprite id 10059), so the mapping cannot be a
// runtime rule. This script fetches PokéAPI's complete pokemon index once — a
// single request, no auth — walks the bundled Showdown dataset, and bakes the
// resolved id for every species name into the committed table. `get_sprites`
// reads only that table, so a species PokéAPI has no entry for stays unmapped
// and the tool reports it as unresolved rather than guessing.
import { writeFileSync } from 'node:fs';
import { Dex } from '@pkmn/dex';

const dex = Dex.mod('gen9');
const toID = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=100000', {
  headers: { 'User-Agent': 'getcompetitive-build-script' },
});
if (!response.ok) {
  throw new Error(`PokéAPI fetch failed: ${response.status}. Retry later or report the upstream outage.`);
}
const index = await response.json();
if (index.results.length < index.count) {
  throw new Error(`PokéAPI index truncated: got ${index.results.length} of ${index.count} — raise the limit.`);
}
const idBySlug = new Map(index.results.map((r) => [toID(r.name), Number(r.url.match(/\/(\d+)\/$/)[1])]));

// Candidate slugs per species name, in preference order. Gender-suffixed
// Showdown names ("Indeedee-F") map to PokéAPI's "-female" slugs, and sexed
// species without a plain entry ("Indeedee", "Basculegion") default to the male
// form, which is PokéAPI's own default artwork. Exact matches always win, so a
// non-gendered form whose name merely ends in m/f (e.g. Rotom-Mow) is never
// touched by the suffix rules.
function candidates(name) {
  const key = toID(name);
  const out = [key];
  if (key.endsWith('f')) out.push(`${key.slice(0, -1)}female`);
  if (key.endsWith('m')) out.push(`${key.slice(0, -1)}male`);
  out.push(`${key}male`, `${key}female`);
  return [...new Set(out)];
}

const table = {};
let mapped = 0;
let missed = 0;
const misses = [];
for (const sp of dex.species.all()) {
  if (sp.isNonstandard === 'CAP') continue;
  const hit = candidates(sp.name).map((c) => idBySlug.get(c)).find((id) => id !== undefined);
  if (hit === undefined) {
    missed++;
    if (misses.length < 12) misses.push(sp.name);
    continue;
  }
  table[toID(sp.name)] = hit;
  mapped++;
}

writeFileSync(
  new URL('../src/sprites.data.ts', import.meta.url),
  [
    '// Generated by scripts/build-sprites.mjs — do not edit by hand.',
    '// Maps toID(species name) to the PokéAPI id whose artwork/sprite that name',
    '// resolves to. Form ids (10001+) follow neither the National Dex number nor the',
    '// forme name, which is why this mapping is a committed table and not a runtime',
    '// rule; the server itself never talks to PokéAPI. Regenerate when the Showdown',
    '// dataset or PokéAPI\u2019s index changes: node scripts/build-sprites.mjs',
    'export default {',
    ...Object.keys(table)
      .sort()
      .map((k) => `  ${JSON.stringify(k)}: ${table[k]},`),
    '} as const;',
    '',
  ].join('\n'),
);

console.log(`Wrote src/sprites.data.ts: ${mapped} of ${mapped + missed} dex species mapped.`);
if (missed) {
  console.log(`Unmapped (reported unresolved at runtime): ${misses.join(', ')}${missed > misses.length ? ` and ${missed - misses.length} more` : ''}.`);
}
