// Maintenance script: regenerate regulation species/mega lists from Bulbapedia.
// Usage: node scripts/extract-regs.mjs  -> writes src/regulations.data.ts
//
// Collapses every form (regional, Rotom appliances, Gourgeist/Lycanroc/Toxtricity/
// Squawkabilly varieties, Mega forms) to its base species, because VGC Species
// Clause is by National Pokedex number: all forms of an eligible species are legal.
import { Dex } from '@pkmn/dex';
import { writeFileSync } from 'node:fs';

const SETS = ['Regulation_Set_M-A', 'Regulation_Set_M-B', 'Regulation_Set_M-C'];

function extractEntries(html, start, end) {
  const slice = html.slice(start, end);
  const out = [];
  const re = /<div class="blacklinks"><b><a href="[^"]*" title="([^"]*)">([\s\S]*?)<\/a><\/b><\/div>/g;
  let m;
  while ((m = re.exec(slice))) {
    const title = m[1];
    const display = m[2].replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
    out.push({ title, display });
  }
  return out;
}

// Base name from the wiki title (e.g. "Raichu (Pokémon)" -> "Raichu").
function baseFromTitle(title) {
  return title.replace(/\s*\(Pokémon\)\s*$/i, '').trim();
}

function collapseToBase(entries) {
  const bases = new Set();
  const unresolved = [];
  for (const e of entries) {
    const name = baseFromTitle(e.title);
    const s = Dex.species.get(name);
    if (!s.exists) {
      unresolved.push(e);
      continue;
    }
    bases.add(s.baseSpecies || s.name);
  }
  return { names: [...bases].sort(), unresolved };
}

const result = {};
for (const set of SETS) {
  const html = await (await fetch(`https://bulbapedia.bulbagarden.net/wiki/${set}`)).text();
  const iElig = html.indexOf('id="Eligible_Pok');
  const iMega = html.indexOf('id="Mega_Evolutions"');
  const eligEnd = iMega > iElig ? iMega : html.indexOf('<h2', iElig + 10);
  const elig = extractEntries(html, iElig, eligEnd);
  const mega = iMega > 0 ? extractEntries(html, iMega, html.indexOf('<h2', iMega + 10)) : [];

  const e = collapseToBase(elig);
  const mg = collapseToBase(mega);
  result[set.replace('Regulation_Set_', '').toLowerCase()] = {
    eligibleSpecies: e.names,
    megaEvolutions: mg.names,
  };
  console.log(set, '| eligible base species:', e.names.length, '| mega species:', mg.names.length, '| unresolved:', e.unresolved.length + mg.unresolved.length);
  for (const u of [...e.unresolved, ...mg.unresolved]) console.log('   unresolved:', JSON.stringify(u));
}

writeFileSync(
  'src/regulations.data.ts',
  `// Generated by scripts/extract-regs.mjs — do not edit by hand.\n` +
    `// Eligible + Mega species are BASE species (Species Clause is by National Pokédex number).\n` +
    `export default ${JSON.stringify(result, null, 2)};\n`,
);
console.log('\nWrote src/regulations.data.ts');
