// Generated by scripts/verify-champions.mjs — do not edit by hand.
// The Champions-exclusive forms bundled with the gen-9 dataset, with the typing
// and base-stat total the official game data was verified against. Every entry
// here is pinned by test/champions.mjs, so a dataset upgrade that silently
// changes a form fails the suite instead of corrupting every analysis.
export default {
  source: "official Champions data via the MunchStats aggregator, diffed by scripts/verify-champions.mjs",
  verifiedAsOf: "2026-09-19",
  forms: [
  {
    "species": "Absol-Mega-Z",
    "types": [
      "Dark",
      "Ghost"
    ],
    "bst": 565
  },
  {
    "species": "Barbaracle-Mega",
    "types": [
      "Rock",
      "Fighting"
    ],
    "bst": 600
  },
  {
    "species": "Baxcalibur-Mega",
    "types": [
      "Dragon",
      "Ice"
    ],
    "bst": 700
  },
  {
    "species": "Chandelure-Mega",
    "types": [
      "Ghost",
      "Fire"
    ],
    "bst": 620
  },
  {
    "species": "Chesnaught-Mega",
    "types": [
      "Grass",
      "Fighting"
    ],
    "bst": 630
  },
  {
    "species": "Chimecho-Mega",
    "types": [
      "Psychic",
      "Steel"
    ],
    "bst": 555
  },
  {
    "species": "Clefable-Mega",
    "types": [
      "Fairy",
      "Flying"
    ],
    "bst": 583
  },
  {
    "species": "Crabominable-Mega",
    "types": [
      "Fighting",
      "Ice"
    ],
    "bst": 578
  },
  {
    "species": "Darkrai-Mega",
    "types": [
      "Dark"
    ],
    "bst": 700
  },
  {
    "species": "Delphox-Mega",
    "types": [
      "Fire",
      "Psychic"
    ],
    "bst": 634
  },
  {
    "species": "Dragalge-Mega",
    "types": [
      "Poison",
      "Dragon"
    ],
    "bst": 594
  },
  {
    "species": "Dragonite-Mega",
    "types": [
      "Dragon",
      "Flying"
    ],
    "bst": 700
  },
  {
    "species": "Drampa-Mega",
    "types": [
      "Normal",
      "Dragon"
    ],
    "bst": 585
  },
  {
    "species": "Eelektross-Mega",
    "types": [
      "Electric"
    ],
    "bst": 615
  },
  {
    "species": "Emboar-Mega",
    "types": [
      "Fire",
      "Fighting"
    ],
    "bst": 628
  },
  {
    "species": "Excadrill-Mega",
    "types": [
      "Ground",
      "Steel"
    ],
    "bst": 608
  },
  {
    "species": "Falinks-Mega",
    "types": [
      "Fighting"
    ],
    "bst": 570
  },
  {
    "species": "Feraligatr-Mega",
    "types": [
      "Water",
      "Dragon"
    ],
    "bst": 630
  },
  {
    "species": "Floette-Mega",
    "types": [
      "Fairy"
    ],
    "bst": 651
  },
  {
    "species": "Froslass-Mega",
    "types": [
      "Ice",
      "Ghost"
    ],
    "bst": 580
  },
  {
    "species": "Garchomp-Mega-Z",
    "types": [
      "Dragon"
    ],
    "bst": 700
  },
  {
    "species": "Glimmora-Mega",
    "types": [
      "Rock",
      "Poison"
    ],
    "bst": 625
  },
  {
    "species": "Golisopod-Mega",
    "types": [
      "Bug",
      "Steel"
    ],
    "bst": 630
  },
  {
    "species": "Golurk-Mega",
    "types": [
      "Ground",
      "Ghost"
    ],
    "bst": 583
  },
  {
    "species": "Greninja-Mega",
    "types": [
      "Water",
      "Dark"
    ],
    "bst": 630
  },
  {
    "species": "Hawlucha-Mega",
    "types": [
      "Fighting",
      "Flying"
    ],
    "bst": 600
  },
  {
    "species": "Heatran-Mega",
    "types": [
      "Fire",
      "Steel"
    ],
    "bst": 700
  },
  {
    "species": "Lucario-Mega-Z",
    "types": [
      "Fighting",
      "Steel"
    ],
    "bst": 625
  },
  {
    "species": "Magearna-Mega",
    "types": [
      "Steel",
      "Fairy"
    ],
    "bst": 700
  },
  {
    "species": "Magearna-Original-Mega",
    "types": [
      "Steel",
      "Fairy"
    ],
    "bst": 700
  },
  {
    "species": "Malamar-Mega",
    "types": [
      "Dark",
      "Psychic"
    ],
    "bst": 582
  },
  {
    "species": "Meganium-Mega",
    "types": [
      "Grass",
      "Fairy"
    ],
    "bst": 625
  },
  {
    "species": "Meowstic-F-Mega",
    "types": [
      "Psychic"
    ],
    "bst": 566
  },
  {
    "species": "Meowstic-M-Mega",
    "types": [
      "Psychic"
    ],
    "bst": 566
  },
  {
    "species": "Pyroar-Mega",
    "types": [
      "Fire",
      "Normal"
    ],
    "bst": 607
  },
  {
    "species": "Raichu-Mega-X",
    "types": [
      "Electric"
    ],
    "bst": 585
  },
  {
    "species": "Raichu-Mega-Y",
    "types": [
      "Electric"
    ],
    "bst": 585
  },
  {
    "species": "Scolipede-Mega",
    "types": [
      "Bug",
      "Poison"
    ],
    "bst": 585
  },
  {
    "species": "Scovillain-Mega",
    "types": [
      "Grass",
      "Fire"
    ],
    "bst": 586
  },
  {
    "species": "Scrafty-Mega",
    "types": [
      "Dark",
      "Fighting"
    ],
    "bst": 588
  },
  {
    "species": "Skarmory-Mega",
    "types": [
      "Steel",
      "Flying"
    ],
    "bst": 565
  },
  {
    "species": "Staraptor-Mega",
    "types": [
      "Fighting",
      "Flying"
    ],
    "bst": 585
  },
  {
    "species": "Starmie-Mega",
    "types": [
      "Water",
      "Psychic"
    ],
    "bst": 620
  },
  {
    "species": "Tatsugiri-Curly-Mega",
    "types": [
      "Dragon",
      "Water"
    ],
    "bst": 575
  },
  {
    "species": "Tatsugiri-Droopy-Mega",
    "types": [
      "Dragon",
      "Water"
    ],
    "bst": 575
  },
  {
    "species": "Tatsugiri-Stretchy-Mega",
    "types": [
      "Dragon",
      "Water"
    ],
    "bst": 575
  },
  {
    "species": "Victreebel-Mega",
    "types": [
      "Grass",
      "Poison"
    ],
    "bst": 590
  },
  {
    "species": "Zeraora-Mega",
    "types": [
      "Electric"
    ],
    "bst": 700
  },
  {
    "species": "Zygarde-Mega",
    "types": [
      "Dragon",
      "Ground"
    ],
    "bst": 778
  }
]
} as const;
