// Generated by scripts/build-meta-history.mjs — do not edit by hand.
// Two 7-day windows of measured usage (last 7 days vs the 7 before) for
// `compare_meta`, keyed by regulation id: per-species usage share and the
// most common species pairs, aggregated from the same tournament source the
// threat list uses. Regenerate with `node scripts/build-meta-history.mjs <regulation>`.
export default { "m-c": {
  "regulation": "m-c",
  "name": "Regulation Set M-C",
  "source": "usage",
  "sourceAsOf": "2026-09-19",
  "note": "Computed from 2091 teams across 29 tournaments in the last 7 days and 1292 teams across the 7 days before that. Windows are rolling: regenerate to slide them forward.",
  "windows": {
    "current": {
      "start": "2026-09-12",
      "end": "2026-09-19",
      "teams": 2091
    },
    "previous": {
      "start": "2026-09-05",
      "end": "2026-09-12",
      "teams": 1292
    }
  },
  "species": [
    {
      "species": "Gholdengo",
      "current": 23.7,
      "previous": 11.8
    },
    {
      "species": "Raichu",
      "current": 15.3,
      "previous": 6.9
    },
    {
      "species": "Arcanine",
      "current": 18.4,
      "previous": 11
    },
    {
      "species": "Milotic",
      "current": 12.1,
      "previous": 7
    },
    {
      "species": "Rillaboom",
      "current": 56.5,
      "previous": 51.8
    },
    {
      "species": "Staraptor",
      "current": 7.5,
      "previous": 3.4
    },
    {
      "species": "Volcarona",
      "current": 6.7,
      "previous": 3.3
    },
    {
      "species": "Gengar",
      "current": 4.6,
      "previous": 1.7
    },
    {
      "species": "Annihilape",
      "current": 3.6,
      "previous": 0.9
    },
    {
      "species": "Metagross",
      "current": 5.5,
      "previous": 2.8
    },
    {
      "species": "Politoed",
      "current": 4.7,
      "previous": 2.2
    },
    {
      "species": "Archaludon",
      "current": 11.3,
      "previous": 9
    },
    {
      "species": "Froslass",
      "current": 7,
      "previous": 5.5
    },
    {
      "species": "Sylveon",
      "current": 11.5,
      "previous": 10.2
    },
    {
      "species": "Indeedee",
      "current": 25.5,
      "previous": 24.3
    },
    {
      "species": "Armarouge",
      "current": 5.8,
      "previous": 4.8
    },
    {
      "species": "Gardevoir",
      "current": 8.8,
      "previous": 8.1
    },
    {
      "species": "Glimmora",
      "current": 3.1,
      "previous": 2.6
    },
    {
      "species": "Salamence",
      "current": 37.2,
      "previous": 37.1
    },
    {
      "species": "Golisopod",
      "current": 16.5,
      "previous": 16.4
    },
    {
      "species": "Grimmsnarl",
      "current": 4.9,
      "previous": 4.9
    },
    {
      "species": "Excadrill",
      "current": 5.5,
      "previous": 5.6
    },
    {
      "species": "Pawmot",
      "current": 3.6,
      "previous": 3.8
    },
    {
      "species": "Primarina",
      "current": 3.7,
      "previous": 3.9
    },
    {
      "species": "Tyranitar",
      "current": 7.7,
      "previous": 8.2
    },
    {
      "species": "Swampert",
      "current": 3.6,
      "previous": 4.1
    },
    {
      "species": "Dragonite",
      "current": 3.6,
      "previous": 4.1
    },
    {
      "species": "Pelipper",
      "current": 12.7,
      "previous": 13.5
    },
    {
      "species": "Farigiraf",
      "current": 15.5,
      "previous": 16.3
    },
    {
      "species": "Hatterene",
      "current": 3.6,
      "previous": 4.5
    },
    {
      "species": "Garchomp",
      "current": 13.1,
      "previous": 14
    },
    {
      "species": "Venusaur",
      "current": 3.5,
      "previous": 4.6
    },
    {
      "species": "Charizard",
      "current": 9.1,
      "previous": 10.7
    },
    {
      "species": "Aerodactyl",
      "current": 2.8,
      "previous": 4.5
    },
    {
      "species": "Delphox",
      "current": 2.5,
      "previous": 4.3
    },
    {
      "species": "Torkoal",
      "current": 4.5,
      "previous": 6.6
    },
    {
      "species": "Lucario",
      "current": 5.9,
      "previous": 8.1
    },
    {
      "species": "Incineroar",
      "current": 33.4,
      "previous": 35.6
    },
    {
      "species": "Sneasler",
      "current": 46.8,
      "previous": 49.3
    },
    {
      "species": "Ninetales",
      "current": 2.5,
      "previous": 5
    }
  ],
  "cores": [
    {
      "core": [
        "Gholdengo",
        "Rillaboom"
      ],
      "current": 19.7,
      "previous": 8.7
    },
    {
      "core": [
        "Raichu",
        "Rillaboom"
      ],
      "current": 12.8,
      "previous": 4.6
    },
    {
      "core": [
        "Gholdengo",
        "Raichu"
      ],
      "current": 9.6,
      "previous": 2.2
    },
    {
      "core": [
        "Arcanine",
        "Rillaboom"
      ],
      "current": 15,
      "previous": 8.4
    },
    {
      "core": [
        "Arcanine",
        "Gholdengo"
      ],
      "current": 8.6,
      "previous": 2.5
    },
    {
      "core": [
        "Arcanine",
        "Raichu"
      ],
      "current": 7.7,
      "previous": 2.3
    },
    {
      "core": [
        "Gholdengo",
        "Salamence"
      ],
      "current": 12.5,
      "previous": 7.2
    },
    {
      "core": [
        "Gholdengo",
        "Sneasler"
      ],
      "current": 11.7,
      "previous": 6.7
    },
    {
      "core": [
        "Rillaboom",
        "Staraptor"
      ],
      "current": 4.5,
      "previous": 0.7
    },
    {
      "core": [
        "Gholdengo",
        "Staraptor"
      ],
      "current": 4.2,
      "previous": 0.5
    },
    {
      "core": [
        "Milotic",
        "Rillaboom"
      ],
      "current": 7,
      "previous": 3.3
    },
    {
      "core": [
        "Raichu",
        "Sneasler"
      ],
      "current": 6.2,
      "previous": 2.6
    },
    {
      "core": [
        "Arcanine",
        "Staraptor"
      ],
      "current": 4.3,
      "previous": 0.9
    },
    {
      "core": [
        "Raichu",
        "Staraptor"
      ],
      "current": 4.2,
      "previous": 0.9
    },
    {
      "core": [
        "Arcanine",
        "Salamence"
      ],
      "current": 11,
      "previous": 7.8
    },
    {
      "core": [
        "Arcanine",
        "Sneasler"
      ],
      "current": 9.4,
      "previous": 6.3
    },
    {
      "core": [
        "Milotic",
        "Salamence"
      ],
      "current": 6.1,
      "previous": 3.1
    },
    {
      "core": [
        "Garchomp",
        "Rillaboom"
      ],
      "current": 7.4,
      "previous": 4.5
    },
    {
      "core": [
        "Gholdengo",
        "Incineroar"
      ],
      "current": 8.1,
      "previous": 5.3
    },
    {
      "core": [
        "Rillaboom",
        "Volcarona"
      ],
      "current": 5.8,
      "previous": 3
    }
  ]
} } as const;
