/**
 * Response levels: compact (default), evidence, debug — the token-efficiency
 * half of the north star. Every compound tool accepts `detail`; the compound
 * layer filters each mode's result through a declarative field-tier spec, so
 * the engines themselves stay untouched.
 *
 * Tier semantics:
 *   compact   conclusions and the numbers needed to reason (default)
 *   evidence  compact plus ranges, benchmarks, assumptions and per-row detail
 *   debug     everything, plus an `engine` block with the data version
 *
 * A mode with no spec returns its full payload at every level — its data is
 * already the answer (species lookups, regulations, pastes). Specs exist only
 * where compaction pays: the heavy analysis outputs.
 */
import { z } from 'zod';
import { readFileSync } from 'node:fs';

export const detailArg = z
  .enum(['compact', 'evidence', 'debug'])
  .optional()
  .describe(
    'How much detail to return: "compact" (default) gives conclusions and the numbers needed to reason; "evidence" adds ranges, benchmarks and per-row detail; "debug" adds provenance and every intermediate. Ask for more only when the reasoning actually needs it — model context is the expensive resource.',
  );

export interface LevelSpec {
  /** Top-level fields present at every level. */
  compact?: string[];
  /** Top-level fields added at evidence and debug. */
  evidence?: string[];
  /** Fields kept per element of an array at compact; dotted paths into the payload. */
  elements?: Record<string, string[]>;
}

const VERSION = (JSON.parse(readFileSync(new URL('../../package.json', import.meta.url), 'utf8')) as { version: string }).version;

function pickFields(source: Record<string, unknown>, keep: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const k of keep) if (k in source) out[k] = source[k];
  return out;
}

/** Apply a keep-list at `path` into a value, projecting array elements along the way. */
function projectInto(value: unknown, path: string[], keep: string[]): unknown {
  if (Array.isArray(value)) {
    return value.map((row) => (row && typeof row === 'object' ? projectInto(row, path, keep) : row));
  }
  if (value && typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    if (path.length === 0) return pickFields(obj, keep);
    const [head, ...rest] = path;
    const next = obj[head];
    if (next === undefined) return obj;
    return { ...obj, [head]: projectInto(next, rest, keep) };
  }
  return value;
}

/**
 * Filter one mode's payload to the requested level. `data` is the inner
 * tool's structuredContent; the returned object becomes the response, with
 * the text regenerated by the caller.
 */
export function applyLevel(
  spec: LevelSpec | undefined,
  data: Record<string, unknown>,
  detail: string | undefined,
  mode: string,
): Record<string, unknown> {
  const level = detail ?? 'compact';
  if (!spec || level === 'debug') {
    if (level === 'debug') return { ...data, engine: { version: VERSION, mode } };
    return data;
  }

  const allowed = new Set<string>([...(spec.compact ?? []), ...(level === 'evidence' ? (spec.evidence ?? []) : [])]);
  const elementPaths = spec.elements ?? {};
  const trimElements = level === 'compact';
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    if (!allowed.has(key)) continue;
    let projected = value;
    if (trimElements) {
      for (const [path, keep] of Object.entries(elementPaths)) {
        if (path === key) projected = projectInto(projected, [], keep);
        else if (path.startsWith(`${key}.`)) projected = projectInto(projected, path.slice(key.length + 1).split('.'), keep);
      }
    }
    out[key] = projected;
  }
  return out;
}

/**
 * Field tiers per mode. Unlisted fields are debug-tier. Modes absent here
 * return their full payload at every level.
 */
export const LEVEL_SPECS: Record<string, LevelSpec> = {
  analyze_team: {
    compact: ['atRiskTypes', 'score', 'speed', 'threatCoverage', 'bringFour'],
    evidence: ['team', 'defensiveWeaknesses', 'offensiveCoverage', 'unknownMoves'],
    elements: {
      'threatCoverage.threats': ['species', 'usage', 'hitMultiplier', 'answerClass', 'answerBy'],
      'threatCoverage.unanswered': ['species'],
    },
  },
  diagnose_team: {
    compact: ['problems', 'candidateChanges'],
    evidence: ['regulation', 'goal', 'unknownMoves', 'note'],
    elements: {
      problems: ['statement', 'severity'],
      candidateChanges: ['kind', 'change', 'confidence'],
    },
  },
  prepare_matchup: {
    compact: ['regulation', 'opponent', 'recommendedBringFour', 'matchupConfidence', 'winConditions', 'lossConditions', 'pokemonToPreserve'],
    evidence: ['likelySets', 'speedTiers', 'relevantDamageCalcs', 'possibleLeads', 'dangerousOpponentLeads', 'note'],
    elements: {
      'recommendedBringFour.picks': ['species', 'score'],
      'recommendedBringFour.leftBehind': ['species'],
      'recommendedBringFour.alternates': ['species'],
      'matchupConfidence': ['score'],
    },
  },
  infer_set: {
    compact: ['priorSets', 'survivingSets', 'candidates'],
    evidence: ['constraints', 'regulation', 'note'],
    elements: {
      candidates: ['item', 'ability', 'nature', 'speed', 'probability'],
    },
  },
  analyze_replay: {
    compact: ['players', 'winner', 'turns', 'teams', 'kos', 'typeRead'],
    evidence: ['teamSize', 'speedConstraints', 'damageEvents', 'unresolvedSpecies', 'note'],
    elements: {
      kos: ['turn', 'move', 'attacker', 'defender'],
    },
  },
  calculate_damage: {
    compact: ['move', 'damageRange', 'koChance', 'description'],
    evidence: ['attacker', 'defender', 'field'],
  },
  calculate_matchups: {
    compact: ['attacker', 'attackerSpeed', 'move'],
    evidence: [],
    elements: {
      matchups: ['defender', 'bestMove', 'damageRange', 'koChance', 'immune'],
    },
  },
  check_speed: {
    compact: ['species', 'level', 'nature', 'finalSpeed', 'modifiers'],
    evidence: ['baseSpe', 'evSpe', 'ivSpe', 'comparison'],
  },
  parse_team: {
    compact: [],
    evidence: ['warnings', 'note'],
    elements: {
      team: ['species', 'item', 'ability', 'nature', 'evs', 'championsPoints', 'moves'],
    },
  },
  check_legality: {
    compact: ['regulation', 'valid', 'violations'],
    evidence: ['status', 'teamSize', 'members', 'mega'],
  },
  optimize_team: {
    compact: ['regulation', 'constraints', 'recommendations'],
    evidence: ['note'],
    elements: {
      'recommendations': ['members', 'score', 'reasons', 'roles'],
    },
  },
};
