/**
 * Sprite URLs for a team: one call for every member, because a team is the unit
 * of work. This tool returns addresses, never image bytes — it reads a committed
 * id table generated by `scripts/build-sprites.mjs`, so the server performs no
 * network I/O and the caller (or the caller's client) does the fetching.
 *
 * PokéAPI assigns form ids above 10000 that follow neither the National Dex
 * number nor the forme name, which is why the mapping is a build-time table
 * rather than a runtime rule; a species PokéAPI has no entry for is reported
 * unresolved instead of guessed at.
 */
import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { toID } from '../dex.js';
import { getChampionsDex } from '../champions.js';
import { ok, wrap, READ_ONLY_ANNOTATIONS } from '../result.js';
import raw from '../sprites.data.js';

const TABLE: Record<string, number> = raw;

const ARTWORK_URL = (id: number) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
const ICON_URL = (id: number) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;

export function registerSpritesTool(server: McpServer) {
  server.registerTool(
    'get_sprites',
    {
      title: 'Get sprite URLs for a team',
      description:
        'Return sprite URLs for a whole team in one call — the team is the unit of work, so pass every species at once instead of calling per member. Each entry carries the resolved species name, its National Dex number, the URL, and alt text; `size: "artwork"` gives the 475\u00d7475 transparent official art (default) and `"icon"` the 96\u00d796 game sprite for compact rows. The response is addresses, not image bytes: the server reads a committed id table generated by `scripts/build-sprites.mjs` and performs no network I/O itself (openWorldHint false), so the caller fetches the URLs client-side. PokéAPI\u2019s form ids follow neither the dex number nor the forme name, which is why the mapping is baked at build time; a species with no PokéAPI entry (cosmetic or totem forms, a few Champions-exclusive Megas) is reported in `unresolved` alongside the rest — one bad name never fails the batch. Species resolve case- and punctuation-insensitively through the same dataset as the other tools. Read-only and offline.',
      annotations: READ_ONLY_ANNOTATIONS,
      inputSchema: {
        species: z
          .array(z.string())
          .min(1)
          .max(30)
          .describe('Species names, e.g. ["Garchomp", "Rotom-Wash", "Salamence-Mega"], in any order; a whole team is the expected payload.'),
        size: z
          .enum(['artwork', 'icon'])
          .optional()
          .describe('Which image the URLs point at: "artwork" (default) is the 475\u00d7475 transparent official art, "icon" is the 96\u00d796 game sprite for a compact row.'),
      },
      outputSchema: {
        sprites: z
          .array(
            z.object({
              species: z.string().describe('Resolved species name, e.g. "Salamence-Mega".'),
              dexNumber: z.number().int().describe('National Dex number of the base species, e.g. 373 for Salamence-Mega.'),
              url: z.string().describe('URL of the PNG; fetch it client-side, this server does no I/O.'),
              altText: z.string().describe('Accessible description of the image.'),
            }),
          )
          .describe('One entry per resolved species, in the order supplied.'),
        unresolved: z
          .array(z.string())
          .optional()
          .describe('Species names as supplied that have no PokéAPI entry; absent when everything resolved.'),
        note: z.string().describe('Why the response is URLs rather than bytes, and what unresolved means.'),
      },
    },
    wrap(async (args: { species: string[]; size?: 'artwork' | 'icon' }) => {
      const dex = getChampionsDex();
      const kind = args.size === 'icon' ? 'in-game sprite' : 'official artwork';
      const urlFor = args.size === 'icon' ? ICON_URL : ARTWORK_URL;
      const sprites: { species: string; dexNumber: number; url: string; altText: string }[] = [];
      const unresolved: string[] = [];

      for (const name of args.species) {
        const sp = dex.species.get(name);
        const id = sp.exists ? TABLE[toID(sp.name)] : undefined;
        if (id === undefined) {
          unresolved.push(name);
          continue;
        }
        sprites.push({
          species: sp.name,
          dexNumber: sp.num,
          url: urlFor(id),
          altText: `${kind} of ${sp.name}`,
        });
      }

      return ok({
        sprites,
        ...(unresolved.length ? { unresolved } : {}),
        note: 'URLs only, no image bytes: the server reads a committed id table (scripts/build-sprites.mjs) and performs no network I/O, so fetch these client-side. A name lands in `unresolved` only when PokéAPI has no entry for that species at all — never because of a fetch failure.',
      });
    }),
  );
}
